### ISSUE TITLE
Massive memory leak in "Devices" panel

### ISSUE THREAD

**Issue by tilda** [intiface/intiface-desktop#129]
Hello! I've come here to write about an issue with the new Playground replacement.

I have a Xbox controller connected to my PC to use with Buttplug/Intiface. When entering the Devices panel, the application almost shows no signs of responding, and also a massive memory leak (see image below):

![image](https://user-images.githubusercontent.com/8301262/121744855-213fd200-cac9-11eb-82e0-b77ae19ac530.png)

Also, attempting to drag the sliders has very noticeable lag.

My guess for this issue existing would be that due to the massive amount of steps exposed, it draws a lot of elements related to the vibration sliders. Using the devtools profiler, it says that there is around 29(!) seconds of blocking time (out of ~45 seconds recording).

**Comment by qdot** [comment]
Oh. Oops. That'd do it heh. Yay 16-bit scalars!

I'll top us out at 100 steps and get this into the patch release most likely happening this weekend, thanks for filing this!
