### ISSUE TITLE
prompts a crash

### ISSUE THREAD

**Issue by key050365** [intiface/intiface-desktop#148]
![TU)K4G$ 4RR9) {3W77F9 R](https://user-images.githubusercontent.com/96135499/146039701-df2568de-638b-4f80-a6df-4eb679235507.png)
[intifacelog.txt](https://github.com/intiface/intiface-desktop/files/7713233/intifacelog.txt)

**Comment by KnightDemons** [comment]
yeah I can't start the server since the update & engine update..

**Comment by qdot** [comment]
@KnightDemons This was most likely due to a bad engine release last night. Update to v47 and things should work.

@key050365 Try doing the same, if you still have issues, please file another bug.
