### ISSUE TITLE
Build on Linux HowTo

### ISSUE THREAD

**Issue by TahomaSoft** [intiface/intiface-desktop#160]
Is there a script or other documentation on how to build this on Linux?  I am trying, but having recursive dependency problems.

Thanks!

**Comment by qdot** [comment]
I wouldn't recommend trying, honestly. This version of the app is deprecated at this point, as we're moving to an immediate mode GUI system. It's been announced as alpha, and probably moving to beta very soon.

https://github.com/qdot/intiface-desktop-egui

**Comment by TahomaSoft** [comment]
Thanks!
