### ISSUE TITLE
Keon Not Detected

### ISSUE THREAD

**Issue by phillmorgan28** [intiface/intiface-desktop#176]
Hi, the Keon is not being detected by over bluetooth on Windows 11. What is strange is that none of my bluetooth devices can see it other than my iPhone and that can only see it AFTER the FeelConnect app is connected to it. It's like it hides and waits for the app to start the connection to a hidden Bluetooth device.

Have these devices been locked down to the mobile app?

**Comment by JadianRadiator** [comment]
I'm starting to think it's an incompatibility with Windows 11.
Because I am having this same issue, and I'm using Windows 11 too.

**Comment by qdot** [comment]
We just found out this morning that there's a new Keon firmware version that ships on devices that've been bought over the past few months. We have to update our device configs for.

**Comment by JadianRadiator** [comment]
were you all busy?
6 days and zero work.

**Comment by qdot** [comment]
You all = one dev who is very busy, yes.

**Comment by qdot** [comment]
That said, there may also be issues with Windows 11 *and* the device naming, so this may take longer to fix than expected. https://github.com/deviceplug/btleplug/issues/267

**Comment by qdot** [comment]
Device config file has been updated to v67, this should fix the naming error at least. Run "Get Updates" in Intiface Desktop and let me know if that works. Otherwise this is the Windows 11 bluetooth issue, which will require more work (but is on my todo list).

**Comment by JadianRadiator** [comment]
that fixed it, it's working now

**Comment by qdot** [comment]
Awesome, closing this then.
