### ISSUE TITLE
When trying to connect to the server trough game, server crashes

### ISSUE THREAD

**Issue by AxiomAtom** [intiface/intiface-desktop#185]
I´m trying to connect this app to a game called FarmD it finds the server but it quickly crashes and sends two error messages:
Websocket server accept error: Protocol(HandshakeIncomplete)
Process Error: ConnectorError("TransportSpecificError(TungsteniteError(Protocol(HandshakeIncomplete)))")

**Comment by qdot** [comment]
Intiface Desktop is no longer supported. We recommend trying Intiface Central: https://intiface.com/central
