### ISSUE TITLE
Websocket Settings menu needs port settings

### ISSUE THREAD

**Issue by valuta1995** [intiface/intiface-desktop#26]
The menu at `Server` > `Advanced` > `Websocket` has the option for Both / Insecure / Secure as non-mutually exclusive options.
Expectation would be mutually exclusive radio selection or two boxes for y/n secure and y/n insecure.

**Comment by qdot** [comment]
Intiface now allows users to run both insecure and secure ports (and IPC!) at the same time, if needed. That said, they need port numbers settings to show that they're now sitting on two different ports, to make it obvious they can both listen at the same time without conflicting. I'll change this bug to do that.

**Comment by qdot** [comment]
Finished in v6
