### ISSUE TITLE
Server does not start when only SSL/TLS option is selected in Websocket Settings

### ISSUE THREAD

**Issue by valuta1995** [intiface/intiface-desktop#28]
When selecting SSL/TLS in `Server` > `Advanced` > `Websocket` as only option the server fails to start. The server does seem to start when any of the two other options (or both) are selected. When no options are selected the server does not start.

**Comment by qdot** [comment]
I'm thinking this may be the CLI itself, as the cert converter in C# might not be working. Needs more review, I'll move this bug over to https://github.com/intiface/intiface-cli-csharp if that ends up being the case.
