### ISSUE TITLE
Vorze A10 Cyclone SA fails to connect

### ISSUE THREAD

**Issue by hotcoconuts** [intiface/intiface-desktop#62]
The device worked previously using the Buttplug server, but now with Intiface fully updated through the update button in the settings, a connection is not formed.
I do have a supported Bluetooth 4.0 dongle, and if I use the Buttplug server, it still works fine.
Turning on logging at the level "Trace" reveals that the line:
```BLE device found: ```
is output several times per second. This happens even when the Cyclone is powered off, so I would assume that this is either just a software glitch, or another BLE device, unnamed, in my vicinity.

EDIT: Reading through more carefully, I can see that there are also lines indicating the discovery of named BLE devices, including:
```
BLE device found: CycSA
No usable device factory available for CycSA.
```
Has support been dropped?

**Comment by hotcoconuts** [comment]
Okay, figured it out. First off, I found the device definition file at AppData\Local\Intiface\buttplug-device-config.json and the device was listed as "CYCSA", and I thought the match might be case-sensitive. Changing CYCSA to CycSA didn't change the behavior of Intiface-desktop, though.
Next, I cloned some repos (intiface-CLI and switched from nuget packages to source code on all Buttplug components) and changed buttplug-device-config.yml in the base Buttplug C# project. Changing "CYCSA" to "CycSA" and running a debug build restored previous functionality.

**Comment by hotcoconuts** [comment]
I see a fix is already ready to merge at https://github.com/buttplugio/buttplug-device-config/pull/5, so I'll just wait for that to go through.

**Comment by qdot** [comment]
Thanks for reporting this! It's a combination of the bug you found (which has been fixed), and a bug in Intiface-desktop where it's not loading the updated device file correctly (which has not been fixed and is why you're still seeing drops, documented at #59 ). I'll try to get these updated soon.
