### ISSUE TITLE
Can only connect via localhost using butplug playground

### ISSUE THREAD

**Issue by LunarTiger** [intiface/intiface-desktop#67]
With the server running and exceptions allowed on the firewall of my computer and port forwarding enabled I seem to only be able to connect via localhost. When I try to connect, using buttplug playground, on the local computer or another computer/phone on the network using 10.0.0.2 (my local i.p. address for my computer) or using a computer/phone outside the network it always gives me the error that it can't connect. If I go to the address 10.0.0.2:12346 to try to accept the security certificate from my local computer or on on the network Chome displays an error that it refused to connect, as if there's no server running. This worked just fine in some of the older versions, though I'm not sure when this started happening as I skipped from version 4 to 14 (or something like that) as I wasn't really using it much at the time.

**Comment by qdot** [comment]
We already discussed this on discord. In chrome, the error is considered to be success because no HTTP page is loaded. I've tested this locally and it seems to work fine for me.
