### ISSUE TITLE
Linux engine install should run setcap

### ISSUE THREAD

**Issue by qdot** [intiface/intiface-desktop#80]
Try to run setcap on the Intiface binary so we aren't stuck with making the user do it. May require popping an auth dialog to do so.

**Comment by notsafeforbread** [comment]
If nothing else, it might be worth checking to see if the program has the capabilities, and notifying the user if they don't. Using the command `getcap` would help.

`getcap IntifaceCLI` returns nothing if it has no capabilities
`getcap -v IntifaceCLI` returns `IntifaceCLI` if it has no capabilities

Both commands should return `IntifaceCLI cap_net_raw=eip` if it's been given the needed capability.

There might be another way to do it via libcap's libraries directly but idk enough about that.

**Comment by notsafeforbread** [comment]
SteamVR has a similar requirement, telling the user it requires superuser access:
![Screenshot_20200920_153706](https://user-images.githubusercontent.com/70742699/93697888-11f2b000-fb59-11ea-81dd-a779ab7b1e53.png)

and then using polkit's `pkexec` to execute the command:
![Screenshot_20200920_153729](https://user-images.githubusercontent.com/70742699/93701130-24211e00-fb5a-11ea-8b53-e1c8ff5ae93f.png)

Could be an idea. (using polkit might restrict this to distros that use systemd?)

**Comment by qdot** [comment]
Yeah, there may need to be a few checks here, as I've also been on systems that don't even have setcap installed by default. :|

**Comment by qdot** [comment]
No longer needed with new dbus btle backend.
