### ISSUE TITLE
Intermittent server crashing

### ISSUE THREAD

**Issue by sippeangelo** [intiface/intiface-desktop#98]
After running for a while the server seems to crash, often during periods of high activity. Not sure if it's related to intiface or the Buttplug server itself, but clicking "Start server" again instantly lets it recover, so maybe an auto-recover option could be helpful for when the server crashes?

![image](https://user-images.githubusercontent.com/262378/101290425-1e061980-37fa-11eb-954d-581195b1506c.png)

Two logs from different computers:
[Intiface log.txt](https://github.com/intiface/intiface-desktop/files/5649418/Intiface.log.txt)
[Initface_Crash_log_VRChat_running_JaceVibe_Mod_12_05_2020_544pm.txt](https://github.com/intiface/intiface-desktop/files/5649412/Initface_Crash_log_VRChat_running_JaceVibe_Mod_12_05_2020_544pm.txt)

**Comment by qdot** [comment]
Ok, this is a crash in buttplug-rs but I'll leave this open until I have a proper issue over there. It looks like if the device is getting sent a ton of commands then disconnects in the middle of it all, the reconnection gets confused. I'll see if I can replicate locally.

Thanks a *ton* for the logs, this is something I've been trying to track down for a while but haven't found a good report yet. I really need to get Sentry into desktop again. :|

**Comment by qdot** [comment]
This ended up being due to a bunch of different things:

- VGB was causing a massive memory leak in buttplug, fixed a while ago
- Buttplug was spamming the logs very hard, causing the process IPC to disconnect weirdly

All of these are fixed and now VGB seems mostly happy with ID. Closing.
